### ISSUE TITLE
[feature/account] 아이디 찾기

### ISSUE THREAD

**Issue by hyeinisfree** [hyeinisfree/init#5]
## Description

> 아이디 찾기 구현하기

## Progress

- ajax를 사용하여 아이디 찾기를 구현한다.

**Comment by hyeinisfree** [comment]
ajax 사용이 너무 까다로워서 그냥 아이디찾기는 안만든다.. 안녕..

**Comment by ynawhocodes** [comment]
아니..왜..혼자 하시나요...?

**Comment by ynawhocodes** [comment]
개인프로젝트로 하실 생각이신가요...?

**Comment by hyeinisfree** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 거의 다 했는데 아쉽잖니

나의 iPhone에서 보냄
